print("hello here's a python Quiz for you ")
print("some basic instructions-")
print("1.first section contain the basic information")
print("2.second section contain the questions")
print("3.And answer given by you will be recorded")
print("SECTION-1")
name=input("Q-1 what is your github username?")
country=input("Q-2 in which country do you live?")
otherLanguage=input("Q-3Do you know any other coding language exept python")
Email=input("Q-4E-mail id")
print("SECTION-B")
Q1=input("Q-1 what is correct way to creating a variable a-_x b-X- c-2X)")
Q2=input("Q-2 what does print function do?")
Q3=input("Q-3what can input function do?")
Q4=input("Q-4 which is your favourite function?")
Q5=input("Q-5 explain in detail about your favourite function")
print("THANKS FOR FILLING THIS FORM")
